version: '3'
services:
  school-front:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:5173"
    image: odamvictor/school-front:latest
  school-back:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URL=mongodb+srv://victorodam:jo08FRn39ag4GJn4@cluster0.uam3il2.mongodb.net/?retryWrites=true&w=majority
    image: odamvictor/school-back:latest
