name: CD Pipeline

on:
  workflow_run:
    workflows: [ "CI Pipeline" ]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Pull Docker Images
        run: |
          sudo docker pull odamvictor/school-front:latest
          sudo docker pull odamvictor/school-back:latest
      - name: Delete Old Docker Containers
        run: |
          sudo docker rm -f school-front-container || true
          sudo docker rm -f school-back-container || true
      - name: Run Docker Containers
        run: |
          sudo docker run -d -p 8080:3000 --name school-back-container odamvictor/school-back
          sudo docker run -d -p 80:5173 --name school-front-container odamvictor/school-front
