name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to Dockerhub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      
    - name: Build and Push Docker Images
      run: |
        docker build -t school-back:latest -f ./backend/Dockerfile ./backend
        docker push odamvictor/school-back:latest
        docker build -t school-front:latest -f ./frontend/Dockerfile ./frontend
        docker push odamvictor/school-front:latest
        
      env:
        DOCKER_BUILDKIT: 1  # Enable BuildKit for better performance
